version: '3'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
  mail:
    image: catatnight/postfix
    environment:
      - smtp_user=username:password
      - maildomain=waikup@example.com
  app:
    image: mdeous/waikup:${WAIKUP_VERSION:-develop}
    environment:
      - DATABASE_HOST=db
      - MAIL_SERVER=mta
    depends_on:
      - db
      - mail
  rp:
    image: nginx:stable-alpine
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - "./docker/nginx/nginx-config.nginx:/etc/nginx/nginx.conf:ro"
      - "./docker/nginx/waikup.nginx:/etc/nginx/sites-enabled/waikup:ro"
      - "./docker/nginx/waikup.crt:/etc/nginx/waikup.crt:ro"
      - "./docker/nginx/waikup.key:/etc/nginx/waikup.key:ro"
      - "./docker/nginx/dh4096.pem:/etc/nginx/dh4096.pem:ro"
    depends_on:
      - app
