version: '3'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
  mail:
    image: catatnight/postfix
    environment:
      - smtp_user=username:password
      - maildomain=waikup@example.com
  app:
    image: waikup:devel
    environment:
      - DATABASE_HOST=db
      - MAIL_SERVER=mta
    volumes:
      - ".:/opt/waikup"
    depends_on:
      - db
      - mail
  rp:
    image: nginx:stable-alpine
    ports:
      - 8080:8080
    volumes:
      - "./docker/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./docker/waikup.nginx:/etc/nginx/sites-enabled/waikup:ro"
    depends_on:
      - app
